steps:
  - name: gcr.io/cloud-builders/docker
    id: Build and push Docker Image
    args: ["build", "-f", "docker/production/Dockerfile", "-t", "gcr.io/fabled-mystery-328210/fb-docs:$COMMIT_SHA", "."]
 
  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/fabled-mystery-328210/fb-docs:$COMMIT_SHA']

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args: ['docker/production/deploy.sh']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'USER=preci'
      - 'PRODUCTION_IP=34.69.23.34'

images:
  - "gcr.io/$PROJECT_ID/fb-docs:$COMMIT_SHA"
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET