// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tracker'}],
  inventorySidebar: [{type: 'autogenerated', dirName: 'inventory'}],
  starlinkSidebar: [{type: 'autogenerated', dirName: 'starlink'}],


  // But you can create a sidebar manually
  
  empsSidebar: [
    
    {
      type: 'category',
      label: 'E-PMS',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'CRM Modules',
          items: [
            'e-pms/crm-modules/bookings',
            'e-pms/crm-modules/broadcasts',
            'e-pms/crm-modules/email',
            'e-pms/crm-modules/pipeline',
          ],
        },
        {
          type: 'category',
          label: 'Guide',
          items: [
            'e-pms/guide/CRM',
            'e-pms/guide/Dashboard',
            'e-pms/guide/PMS',
          ], 
        },
        {
          type: 'category',
          label: 'PMS Modules',
          items: [
            'e-pms/pms-modules/all-vessel-equipment-list',
            'e-pms/pms-modules/company-list',
            'e-pms/pms-modules/contact-list',
            'e-pms/pms-modules/upcoming-services-list',
            'e-pms/pms-modules/vessel-list',
          ],  
        },
        {
          type: 'category',
          label: 'Settings',
          items: [
            'e-pms/settings/email-settings',
            'e-pms/settings/equipment',
            'e-pms/settings/roles-and-permissions',
            'e-pms/settings/sea-areas',
            'e-pms/settings/services',
            'e-pms/settings/user',
            'e-pms/settings/vessel-weight',
          ],   
        },
      ],
    },
  ],
};

export default sidebars;
