version: '3.6'

services:
  fieldbase-docker:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: 'gcr.io/fabled-mystery-328210/fb-docs:latest'
    deploy:
      replicas: 2
    restart: on-failure
    ports:
      - '3005:3005'